# Generated by Django 3.1.5 on 2021-02-06 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import listing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RealestateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('state_number', models.IntegerField()),
                ('slug', models.SlugField(allow_unicode=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('neiborhood', models.CharField(blank=True, max_length=200, null=True, verbose_name='neiborhood')),
                ('description', models.TextField(verbose_name='description')),
                ('square_meter', models.FloatField(default=1, verbose_name='square meter')),
                ('n_bedrooms', models.IntegerField(default=1, verbose_name='number of bedrooms')),
                ('n_bathrooms', models.IntegerField(default=1, verbose_name='number of bathrooms')),
                ('garage', models.BooleanField(default=False, verbose_name='garage')),
                ('listing_image_main', models.ImageField(upload_to=listing.models.image_filepath, verbose_name='main image')),
                ('listing_image_1', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_2', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_3', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_4', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_5', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_6', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_7', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_8', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_9', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_10', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_11', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_12', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_13', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_14', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('listing_image_15', models.ImageField(blank=True, null=True, upload_to=listing.models.image_filepath)),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='listing.city', verbose_name='city')),
                ('realeste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.realestatetype', verbose_name='Realestate Type')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.realtor', verbose_name='realtor')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='listing.state', verbose_name='state')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.transactiontype', verbose_name='Transaction Type')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listing.state', verbose_name='state'),
        ),
    ]
