# Generated by Django 3.1.5 on 2021-02-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20210206_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='realeste_type',
            new_name='realestate_type',
        ),
    ]
