# Generated by Django 3.1.5 on 2021-02-08 22:14

from django.db import migrations, models
import django.db.models.deletion
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_listing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_image_main',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_10',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_11',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_12',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_13',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_14',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_15',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_5',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_6',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_7',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_8',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_9',
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=listing.models.image_filepath)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listing')),
            ],
        ),
    ]
