# Generated by Django 3.1.5 on 2021-02-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20210208_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
    ]
