# Generated by Django 3.1.5 on 2021-02-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(1, 'male'), (2, 'female'), (3, 'unknown')], default=3, max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='userimages/default.png', null=True, upload_to='userimages/', verbose_name='profile image'),
        ),
    ]
