# Generated by Django 3.1.5 on 2021-02-02 15:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210202_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'unknown')], default=3, max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=accounts.models.image_default, null=True, upload_to=accounts.models.image_filepath, verbose_name='profile image'),
        ),
    ]
