# Generated by Django 3.1.5 on 2021-02-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210203_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='slug'),
        ),
    ]
