# Generated by Django 3.1.5 on 2021-02-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210204_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='username_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='username id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], default=3, max_length=10, verbose_name='gender'),
        ),
    ]
